@ECHO OFF
IF EXIST "%ProgramFiles%\Microsoft BizTalk Server 2009\BTSmmc.msc" GOTO INSTALLED
GOTO INSTALL

:INSTALL
ECHO Install Biztalk 2009
@ECHO ON
[BASEINSTALLDIR]Biztalk2009\setup /CABPATH [BASEINSTALLDIR]Biztalk2009CAB\BTSRedistW2K8EN32.cab /PASSIVE /ADDLOCAL ALL
@ECHO OFF
GOTO END

:INSTALLED
ECHO Biztalk 2009 Already installed
:END
